name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SMVERSION: 1.11
      MMVERSION: 1.11
    
    steps:
    - uses: actions/checkout@v2
      
    - name: Build
      run: |
        shopt -s extglob

        mkdir sm build plugins
        cd sm

        wget --input-file=http://sourcemod.net/smdrop/$SMVERSION/sourcemod-latest-linux
        tar -xzf $(cat sourcemod-latest-linux)

        cd ../
        cp -R !(sm) sm/addons/sourcemod/
        cd sm/addons/sourcemod/scripting

        wget "https://raw.githubusercontent.com/asherkin/TF2Items/master/pawn/tf2items.inc" -O include/tf2items.inc
        wget "https://raw.githubusercontent.com/KyleSanderson/SteamWorks/master/Pawn/includes/SteamWorks.inc" -O include/SteamWorks.inc

        sed -i -e "s/char sData\[\]/char\[\] sData/g" -e "s/int data\[\]/int\[\] data/g" include/SteamWorks.inc

        chmod +x ./spcomp
        ./spcomp instagib.sp

        mv instagib.smx ../../../../plugins
        cd ../../../../

        rm -d -R sm

        cd scripting
        rm -d -R !(include)
        cd ../

        mv !(build) build
              
    - name: Upload
      if: github.event_name == 'push'
      uses: actions/upload-artifact@v2
      with:
        name: TF2Instagib-${{github.head_ref}}-${{github.run_number}}
        path: build/